management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.learn.microservices.springboot: DEBUG