management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  ignored-services: '*'
#  prefix: /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
#    licensestatic:
#      path: /licensestatic/**
#      #url: http://licenseservice-static:8081
#      serviceId: licensestatic
#
## Following configuration is for manual mapping of routes using static URLs and when you need to provide list of
##  individual service instances that ribbon will load balance against instead of single route.
#
#ribbon:
#  eureka:
#    enabled: false #This config will cut Ribbon support with Eureka. So no cache of service mapping. It will call
#    #Eureka everytime to resolve service location. Cause more load on Eureka
#licensestatic:
#  ribbon:
#    listOfServers: http://licenseservice-static1:8081,http://licenseservice-static2:


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.learn.microservices.springboot: DEBUG