server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/licensingservice
#         searchLocations: file:///D:/Learnings/SpringBoot-Microservices/licensing-service/confsvr/src/main/resources/config/licensingservice
